name: docs

on:
  push:
    paths-ignore:
      - docs/**
    branches:
      - master

jobs:
  make-docs:
    name: make docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: make docs
        run: cd docsrc && make html && mkdir /home/docs && cp -r build /home/docs
      - name: update file and push to remote
        run: |
          git config --global user.name 'Action Bot'
          git config --global user.email 'action-bot@users.noreply.github.com'

          git checkout gh-pages
          cp /home/docs .

          git commit -m "auto-update docs"
          git push
