name: docs

on: [push]
  #push:
  #  branches:
  #    - master

jobs:
  make-docs:
    name: make docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: make docs
        run: cd docsrc && make github
      - name: update file and push to remote
        run: |
          git add docs/**
          git commit -m "build sphinx docs"
          git push
